version: '3.1'

services:
  wishlist-service:
    container_name: wishlist-service
    depends_on:
      - wishlist-mongo-db
    networks:
      - mongo-network-wishlist
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - "/app/dist"
    ports:
      - 3000:3000
  wishlist-mongo-db:
    logging:
      driver: "none"
    container_name: wishlist-mongo-db
    image: mongo
    restart: always
    volumes:
      - wishlist-mongo:/data/db
      - .docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-network-wishlist
    ports:
      - '27017:27017'
    env_file:
      - .env

volumes:
  wishlist-mongo:
networks:
  mongo-network-wishlist:
    driver: bridge